In [1]:
import pandas as pd

In [3]:
i = pd.read_csv("inventory.csv")

In [15]:
Staten__island = i.query("location == 'Staten Island'")

In [17]:
Staten__island

        location  product_type         product_description  quantity  price
0  Staten Island         seeds                       daisy         4   6.99
1  Staten Island         seeds                  calla lily        46  19.99
2  Staten Island         seeds                      tomato        85  13.99
3  Staten Island  garden tools                        rake         4  13.99
4  Staten Island  garden tools                 wheelbarrow         0  89.99
5  Staten Island  garden tools                       spade        93  19.99
6  Staten Island  pest_control               insect killer        74  12.99
7  Staten Island  pest_control                 weed killer         8  23.99
8  Staten Island       planter  20 inch terracotta planter         0  17.99
9  Staten Island       planter      8 inch plastic planter        53   3.99

In [11]:
i.head(20)

         location  product_type         product_description  quantity  price
0   Staten Island         seeds                       daisy         4   6.99
1   Staten Island         seeds                  calla lily        46  19.99
2   Staten Island         seeds                      tomato        85  13.99
3   Staten Island  garden tools                        rake         4  13.99
4   Staten Island  garden tools                 wheelbarrow         0  89.99
5   Staten Island  garden tools                       spade        93  19.99
6   Staten Island  pest_control               insect killer        74  12.99
7   Staten Island  pest_control                 weed killer         8  23.99
8   Staten Island       planter  20 inch terracotta planter         0  17.99
9   Staten Island       planter      8 inch plastic planter        53   3.99
10       Brooklyn         seeds                       daisy        50   6.99
11       Brooklyn         seeds                  calla lily         0  19.99
12       Brooklyn         seeds                      tomato         0  13.99
13       Brooklyn  garden tools                        rake        15  13.99
14       Brooklyn  garden tools                 wheelbarrow        82  89.99
15       Brooklyn  garden tools                       spade        36  19.99
16       Brooklyn  pest_control               insect killer        80  12.99
17       Brooklyn  pest_control                 weed killer        76  23.99
18       Brooklyn       planter  20 inch terracotta planter         5  17.99
19       Brooklyn       planter      8 inch plastic planter        26   3.99

In [19]:
prod_req = Staten__island.product_description

In [21]:
prod_req

0                         daisy
1                    calla lily
2                        tomato
3                          rake
4                   wheelbarrow
5                         spade
6                 insect killer
7                   weed killer
8    20 inch terracotta planter
9        8 inch plastic planter
Name: product_description, dtype: object

In [25]:
seed_req = i[(i.location == "Brooklyn") & (i.product_type == "seeds")]

In [29]:
types_of_seeds = i[(i.location == "Brooklyn") & (i.product_type == "seeds")].product_description.values

In [31]:
i['in_stock'] = i['quantity'].apply(lambda x: x > 0)

In [33]:
i

,location,product_type,product_description,quantity,price,in_stock
0,Staten Island,seeds,daisy,4,6.99,True
1,Staten Island,seeds,calla lily,46,19.99,True
2,Staten Island,seeds,tomato,85,13.99,True
3,Staten Island,garden tools,rake,4,13.99,True
4,Staten Island,garden tools,wheelbarrow,0,89.99,False
5,Staten Island,garden tools,spade,93,19.99,True
6,Staten Island,pest_control,insect killer,74,12.99,True
7,Staten Island,pest_control,weed killer,8,23.99,True
8,Staten Island,planter,20 inch terracotta planter,0,17.99,False
9,Staten Island,planter,8 inch plastic planter,53,3.99,True
10,Brooklyn,seeds,daisy,50,6.99,True
11,Brooklyn,seeds,calla lily,0,19.99,False
12,Brooklyn,seeds,tomato,0,13.99,False
13,Brooklyn,garden tools,rake,15,13.99,True
14,Brooklyn,garden tools,wheelbarrow,82,89.99,True
15,Brooklyn,garden tools,spade,36,19.99,True
16,Brooklyn,pest_control,insect killer,80,12.99,True
17,Brooklyn,pest_control,weed killer,76,23.99,True
18,Brooklyn,planter,20 inch terracotta planter,5,17.99,True
19,Brooklyn,planter,8 inch plastic planter,26,3.99,True
20,Queens,seeds,daisy,57,6.99,True
21,Queens,seeds,calla lily,95,19.99,True
22,Queens,seeds,tomato,45,13.99,True
23,Queens,garden tools,rake,21,13.99,True
24,Queens,garden tools,wheelbarrow,98,89.99,True
25,Queens,garden tools,spade,26,19.99,True
26,Queens,pest_control,insect killer,0,12.99,False
27,Queens,pest_control,weed killer,16,23.99,True
28,Queens,planter,20 inch terracotta planter,87,17.99,True

In [35]:
i["total_value"] = i.price * i.quantity

In [37]:
i

,location,product_type,product_description,quantity,price,in_stock,total_value
0,Staten Island,seeds,daisy,4,6.99,True,27.96
1,Staten Island,seeds,calla lily,46,19.99,True,919.54
2,Staten Island,seeds,tomato,85,13.99,True,1189.15
3,Staten Island,garden tools,rake,4,13.99,True,55.96
4,Staten Island,garden tools,wheelbarrow,0,89.99,False,0.00
5,Staten Island,garden tools,spade,93,19.99,True,1859.07
6,Staten Island,pest_control,insect killer,74,12.99,True,961.26
7,Staten Island,pest_control,weed killer,8,23.99,True,191.92
8,Staten Island,planter,20 inch terracotta planter,0,17.99,False,0.00
9,Staten Island,planter,8 inch plastic planter,53,3.99,True,211.47
10,Brooklyn,seeds,daisy,50,6.99,True,349.50
11,Brooklyn,seeds,calla lily,0,19.99,False,0.00
12,Brooklyn,seeds,tomato,0,13.99,False,0.00
13,Brooklyn,garden tools,rake,15,13.99,True,209.85
14,Brooklyn,garden tools,wheelbarrow,82,89.99,True,7379.18
15,Brooklyn,garden tools,spade,36,19.99,True,719.64
16,Brooklyn,pest_control,insect killer,80,12.99,True,1039.20
17,Brooklyn,pest_control,weed killer,76,23.99,True,1823.24
18,Brooklyn,planter,20 inch terracotta planter,5,17.99,True,89.95
19,Brooklyn,planter,8 inch plastic planter,26,3.99,True,103.74
20,Queens,seeds,daisy,57,6.99,True,398.43
21,Queens,seeds,calla lily,95,19.99,True,1899.05
22,Queens,seeds,tomato,45,13.99,True,629.55
23,Queens,garden tools,rake,21,13.99,True,293.79
24,Queens,garden tools,wheelbarrow,98,89.99,True,8819.02
25,Queens,garden tools,spade,26,19.99,True,519.74
26,Queens,pest_control,insect killer,0,12.99,False,0.00
27,Queens,pest_control,weed killer,16,23.99,True,383.84
28,Queens,planter,20 inch terracotta planter,87,17.99,True,1565.13

In [55]:
combine_lambda = lambda x: f"{x['product_type']} - {x['product_description']}"

i["full_description"] = i.apply(combine_lambda, axis=1)

In [57]:
i

,location,product_type,product_description,quantity,price,in_stock,total_value,full_description
0,Staten Island,seeds,daisy,4,6.99,True,27.96,seeds - daisy
1,Staten Island,seeds,calla lily,46,19.99,True,919.54,seeds - calla lily
2,Staten Island,seeds,tomato,85,13.99,True,1189.15,seeds - tomato
3,Staten Island,garden tools,rake,4,13.99,True,55.96,garden tools - rake
4,Staten Island,garden tools,wheelbarrow,0,89.99,False,0.00,garden tools - wheelbarrow
5,Staten Island,garden tools,spade,93,19.99,True,1859.07,garden tools - spade
6,Staten Island,pest_control,insect killer,74,12.99,True,961.26,pest_control - insect killer
7,Staten Island,pest_control,weed killer,8,23.99,True,191.92,pest_control - weed killer
8,Staten Island,planter,20 inch terracotta planter,0,17.99,False,0.00,planter - 20 inch terracotta planter
9,Staten Island,planter,8 inch plastic planter,53,3.99,True,211.47,planter - 8 inch plastic planter
10,Brooklyn,seeds,daisy,50,6.99,True,349.50,seeds - daisy
11,Brooklyn,seeds,calla lily,0,19.99,False,0.00,seeds - calla lily
12,Brooklyn,seeds,tomato,0,13.99,False,0.00,seeds - tomato
13,Brooklyn,garden tools,rake,15,13.99,True,209.85,garden tools - rake
14,Brooklyn,garden tools,wheelbarrow,82,89.99,True,7379.18,garden tools - wheelbarrow
15,Brooklyn,garden tools,spade,36,19.99,True,719.64,garden tools - spade
16,Brooklyn,pest_control,insect killer,80,12.99,True,1039.20,pest_control - insect killer
17,Brooklyn,pest_control,weed killer,76,23.99,True,1823.24,pest_control - weed killer
18,Brooklyn,planter,20 inch terracotta planter,5,17.99,True,89.95,planter - 20 inch terracotta planter
19,Brooklyn,planter,8 inch plastic planter,26,3.99,True,103.74,planter - 8 inch plastic planter
20,Queens,seeds,daisy,57,6.99,True,398.43,seeds - daisy
21,Queens,seeds,calla lily,95,19.99,True,1899.05,seeds - calla lily
22,Queens,seeds,tomato,45,13.99,True,629.55,seeds - tomato
23,Queens,garden tools,rake,21,13.99,True,293.79,garden tools - rake
24,Queens,garden tools,wheelbarrow,98,89.99,True,8819.02,garden tools - wheelbarrow
25,Queens,garden tools,spade,26,19.99,True,519.74,garden tools - spade
26,Queens,pest_control,insect killer,0,12.99,False,0.00,pest_control - insect killer
27,Queens,pest_control,weed killer,16,23.99,True,383.84,pest_control - weed killer
28,Queens,planter,20 inch terracotta planter,87,17.99,True,1565.13,planter - 20 inch terracotta planter

In [66]:
i["X"] = i.apply(lambda row :f"{row["product_type"]} - {row["product_description"]}",axis=1)

In [72]:
i.drop("X",axis=1,inplace = True)

In [74]:
i

,location,product_type,product_description,quantity,price,in_stock,total_value,full_description
0,Staten Island,seeds,daisy,4,6.99,True,27.96,seeds - daisy
1,Staten Island,seeds,calla lily,46,19.99,True,919.54,seeds - calla lily
2,Staten Island,seeds,tomato,85,13.99,True,1189.15,seeds - tomato
3,Staten Island,garden tools,rake,4,13.99,True,55.96,garden tools - rake
4,Staten Island,garden tools,wheelbarrow,0,89.99,False,0.00,garden tools - wheelbarrow
5,Staten Island,garden tools,spade,93,19.99,True,1859.07,garden tools - spade
6,Staten Island,pest_control,insect killer,74,12.99,True,961.26,pest_control - insect killer
7,Staten Island,pest_control,weed killer,8,23.99,True,191.92,pest_control - weed killer
8,Staten Island,planter,20 inch terracotta planter,0,17.99,False,0.00,planter - 20 inch terracotta planter
9,Staten Island,planter,8 inch plastic planter,53,3.99,True,211.47,planter - 8 inch plastic planter
10,Brooklyn,seeds,daisy,50,6.99,True,349.50,seeds - daisy
11,Brooklyn,seeds,calla lily,0,19.99,False,0.00,seeds - calla lily
12,Brooklyn,seeds,tomato,0,13.99,False,0.00,seeds - tomato
13,Brooklyn,garden tools,rake,15,13.99,True,209.85,garden tools - rake
14,Brooklyn,garden tools,wheelbarrow,82,89.99,True,7379.18,garden tools - wheelbarrow
15,Brooklyn,garden tools,spade,36,19.99,True,719.64,garden tools - spade
16,Brooklyn,pest_control,insect killer,80,12.99,True,1039.20,pest_control - insect killer
17,Brooklyn,pest_control,weed killer,76,23.99,True,1823.24,pest_control - weed killer
18,Brooklyn,planter,20 inch terracotta planter,5,17.99,True,89.95,planter - 20 inch terracotta planter
19,Brooklyn,planter,8 inch plastic planter,26,3.99,True,103.74,planter - 8 inch plastic planter
20,Queens,seeds,daisy,57,6.99,True,398.43,seeds - daisy
21,Queens,seeds,calla lily,95,19.99,True,1899.05,seeds - calla lily
22,Queens,seeds,tomato,45,13.99,True,629.55,seeds - tomato
23,Queens,garden tools,rake,21,13.99,True,293.79,garden tools - rake
24,Queens,garden tools,wheelbarrow,98,89.99,True,8819.02,garden tools - wheelbarrow
25,Queens,garden tools,spade,26,19.99,True,519.74,garden tools - spade
26,Queens,pest_control,insect killer,0,12.99,False,0.00,pest_control - insect killer
27,Queens,pest_control,weed killer,16,23.99,True,383.84,pest_control - weed killer
28,Queens,planter,20 inch terracotta planter,87,17.99,True,1565.13,planter - 20 inch terracotta planter